package cli

import (
	"errors"
	"flag"
	"fmt"
	"io"

	"gpt_server/internal/config"
)

func runAPI(args []string, stdout io.Writer, store *config.Store) error {
	if err := requireStore(store); err != nil {
		return err
	}
	fs := flag.NewFlagSet("api", flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	list := fs.Bool("list", false, "list group api entrypoints")
	gen := fs.Bool("genapi", false, "removed: api is generated by auth")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *gen {
		return errors.New("--genapi has been removed; run ./main auth to create or join a group and generate the group api")
	}
	if !*list {
		return errors.New("api requires --list")
	}
	cfg, err := store.Load()
	if err != nil {
		return err
	}
	if len(cfg.Groups) == 0 {
		_, _ = fmt.Fprintln(stdout, "no groups")
		return nil
	}
	for _, group := range cfg.Groups {
		_, _ = fmt.Fprintf(stdout, "%s\t%s\t%s\tusers=%d\n", group.GID, group.GName, group.API, len(group.Users))
	}
	return nil
}
